
const areas = [
  {name:'Ahorro e inversión',icon:'↗',questions:{
    inicial:['Sigo un presupuesto y pago mis facturas a tiempo.','Tengo un fondo de emergencia para gastos inesperados.','Conozco el total de mis deudas y cuánto interés pago por ellas.','Entiendo el interés compuesto y el valor del dinero en el tiempo.'],
    intermedio:['Conozco mi patrimonio neto.','Sé explicar la diferencia entre ahorrar e invertir.','Conozco mi tolerancia al riesgo.','Entiendo cómo la inflación reduce el valor de mis ahorros.'],
    avanzado:['Sé explicar la diferencia entre una acción y un bono.','Entiendo la relación inversa entre los bonos y las tasas de interés.','Sé diferenciar un fondo mutuo de un ETF.','Mis inversiones están bien diversificadas.']},learn:'Refuerza presupuesto, fondo de emergencia e interés compuesto antes de asumir más riesgo.'},
  {name:'Inversión para el retiro',icon:'⌛',questions:{
    inicial:['Tengo una imagen clara de mi retiro y he estimado cuánto necesitaré.','Conozco mi perfil de riesgo y elijo inversiones acordes.','Conozco vehículos de retiro como Roth IRA o 401(k).'],
    intermedio:['Tengo una meta anual para aumentar mis aportaciones al retiro.','Reviso regularmente que mi portafolio coincida con mi horizonte y riesgo.','He considerado la inflación en mis necesidades de ingreso para el retiro.'],
    avanzado:['Comprendo la asignación de activos y cómo rebalancear un portafolio.','He investigado inversiones que generan ingresos, como dividendos y anualidades.','Tengo un plan para minimizar impuestos durante el retiro.']},learn:'Calcula tu meta de retiro y automatiza aportaciones periódicas según tu horizonte.'},
  {name:'Impuestos',icon:'%',questions:{
    inicial:['Sé preparar y presentar mis impuestos o trabajo con un profesional.','Estoy al corriente con mis impuestos federales y estatales.','Conservo copias de mis declaraciones de los últimos tres años.'],
    intermedio:['Aprovecho al máximo las cuentas de ahorro con ventajas fiscales.','Comprendo por qué recibir un gran reembolso no siempre es lo óptimo.'],
    avanzado:['Considero realizar pérdidas de inversiones para compensar ganancias.','Entiendo las ventajas fiscales de donar activos en especie.']},learn:'Organiza tus documentos y conoce las cuentas con ventajas fiscales disponibles en tu país.'},
  {name:'Seguros',icon:'◇',questions:{
    inicial:['Tengo un inventario de los bienes y objetos de valor de mi hogar.','Reviso mis pólizas con regularidad.','Tengo cobertura suficiente para proteger mis ingresos y deudas.','Los beneficiarios de mis pólizas están actualizados.'],
    intermedio:['Conozco los beneficios de salud posteriores al retiro disponibles para mí.','He organizado mi seguro médico para mis necesidades actuales y futuras.','Reviso coberturas y precios en momentos importantes de mi vida.'],
    avanzado:['He considerado un seguro de cuidados a largo plazo.','Entiendo cómo un seguro de vida puede integrarse en mi planificación patrimonial.']},learn:'Haz un inventario de riesgos y revisa coberturas, exclusiones y beneficiarios una vez al año.'},
  {name:'Planificación patrimonial',icon:'⌂',questions:{
    inicial:['He preparado un testamento que especifica cómo dividir mis activos.','He designado beneficiarios en mis cuentas y pólizas.','He nombrado un albacea y guardo mis documentos en un lugar seguro.'],
    intermedio:['Tengo un poder duradero para mis finanzas y atención médica.','Tengo directrices médicas anticipadas y he evaluado un fideicomiso.','He considerado las obligaciones que recaerían sobre mi patrimonio.'],
    avanzado:['He considerado estrategias para maximizar mi legado y reducir su carga fiscal.','Gestiono eficazmente mis donaciones y activos benéficos.']},learn:'Empieza por testamento, beneficiarios y poderes; comunica dónde están tus documentos.'},
  {name:'Ingresos en el retiro',icon:'≈',questions:{
    inicial:['He realizado un inventario de mis activos.','He preparado un presupuesto para el retiro.','Conozco mis fuentes futuras de ingreso y opciones de beneficios.','Comprendo mis opciones de cobertura médica y sus costos estimados.'],
    intermedio:['Tengo un plan de vivienda para cuando cambien mi salud o movilidad.','Tengo un plan de contingencia ante discapacidad, enfermedad o fallecimiento de mi pareja.'],
    avanzado:['Sé cómo retirar fondos de forma fiscalmente eficiente.','Tengo una estrategia para generar flujo de efectivo predecible en el retiro.','He evaluado si las anualidades son adecuadas para mi situación.']},learn:'Proyecta ingresos y gastos del retiro e incluye salud, vivienda e inflación.'}
];
const options=[{label:'Sí, totalmente',value:'yes',score:1},{label:'En parte',value:'partial',score:.5},{label:'No',value:'no',score:0},{label:'No aplica a mi situación',value:'na',score:null},{label:'No lo sé',value:'unknown',score:null}];
const areaIntroductions=[
  'Empezaremos por cómo organizas tu dinero, construyes un fondo de emergencia y haces crecer tus ahorros.',
  'Aquí veremos cómo imaginas tu retiro, cómo inviertes para alcanzarlo y qué decisiones pueden darte más tranquilidad.',
  'En esta sección exploraremos tus hábitos fiscales, tus documentos y las oportunidades para planificar mejor tus impuestos.',
  'Ahora revisaremos cómo proteges tus ingresos, tu salud, tus bienes y a las personas importantes para ti.',
  'Esta parte se centra en testamentos, beneficiarios y decisiones que ayudan a cuidar tu patrimonio en el futuro.',
  'Cerraremos mirando tus ingresos, gastos y estrategias para construir un retiro más predecible.'
];
const courseRecommendations=[
  {id:'money',name:'¿Por qué no nos alcanza el dinero?',url:'https://hispanic-wealth.teachable.com/l/pdp/por-que-no-nos-alcanza-el-dinero',thumbnail:null,questionRefs:['0-0-0','5-0-1'],areaIndices:[0,5],reason:'Te puede ayudar a ordenar gastos, presupuesto y decisiones cotidianas con el dinero.'},
  {id:'emergency',name:'Fondo de emergencias',url:'https://hispanic-wealth.teachable.com/p/fondo-de-emergencias2',thumbnail:null,questionRefs:['0-0-1'],areaIndices:[0],reason:'Puede darte una guía práctica para preparar reservas frente a imprevistos.'},
  {id:'fraud',name:'Prevención de fraudes y robo de identidad',url:'https://hispanic-wealth.teachable.com/p/prevencion-de-fraudes-y-robo-de-identidad1',thumbnail:null,questionRefs:[],areaIndices:[],reason:'Una opción para profundizar en la protección de tu información y tu seguridad financiera.'}
];
const feedbackMessages={
  high:['¡Muy bien! Cerraste esta sección con una base sólida. Ahora veamos cómo se conecta con el siguiente tema.','Tu desempeño muestra dominio en varias ideas importantes de esta área. El siguiente paso puede ayudarte a ampliar esa perspectiva.'],
  good:['Vas avanzando: reconoces varios conceptos importantes y hay algunos matices que vale la pena seguir explorando.','Buen trabajo en esta sección. Ya tienes una base útil; ahora pondremos a prueba nuevas decisiones financieras.'],
  developing:['Esta sección abrió una oportunidad concreta para aprender. Algunas ideas simples pueden hacer una diferencia en tus decisiones.','Ya identificaste parte del terreno. Continuemos para descubrir qué otros conceptos pueden fortalecer tu mapa financiero.'],
  foundation:['Gracias por recorrer esta sección. Aquí hay conceptos fundamentales que pueden darte más claridad y confianza paso a paso.','Cada respuesta aporta información útil sobre tu punto de partida. La siguiente sección nos ayudará a completar el panorama.']
};
let state={area:0,level:0,index:0,answers:{},learn:[],wrong:0}; const levels=['inicial','intermedio','avanzado'];
const $=id=>document.getElementById(id); const views=['welcomeView','quizView','resultsView'];
function show(id){views.forEach(v=>$(v).classList.toggle('active',v===id));window.scrollTo(0,0)}
function key(){return `${state.area}-${state.level}-${state.index}`}
function question(){return areas[state.area].questions[levels[state.level]][state.index]}
function save(){localStorage.setItem('claraProgress',JSON.stringify(state))}
function render(){const area=areas[state.area], qs=area.questions[levels[state.level]], total=areas.reduce((n,a)=>n+Object.values(a.questions).flat().length,0),done=Object.keys(state.answers).length;
  $('areaName').textContent=area.name;$('progressLabel').textContent=`${state.area+1} de ${areas.length} áreas`;$('progressBar').style.width=`${Math.max(3,done/total*100)}%`;
  $('levelPill').textContent=`NIVEL ${levels[state.level].toUpperCase()}`;$('questionCount').textContent=`Pregunta ${state.index+1} de ${qs.length}`;$('questionText').textContent=question();
  $('answers').innerHTML=options.map((o,i)=>`<button class="answer ${state.answers[key()]?.value===o.value?'selected':''}" data-value="${o.value}"><span class="answer-key">${String.fromCharCode(65+i)}</span>${o.label}</button>`).join('');
  $('learnMore').checked=state.learn.includes(key());$('nextButton').disabled=!state.answers[key()];$('backButton').disabled=done===0;
  $('answers').querySelectorAll('.answer').forEach(b=>b.onclick=()=>select(b.dataset.value));updateCoach();
}
function select(value){const o=options.find(x=>x.value===value);state.answers[key()]={value,score:o.score,area:state.area,level:state.level,q:question()};render();save()}
function updateCoach(){const answered=Object.values(state.answers).filter(a=>a.area===state.area),strong=answered.filter(a=>a.score===1).length;
  if(strong>=3){$('coachKicker').textContent='¡ESO ES!';$('coachTitle').innerHTML='Tu base se ve<br>muy sólida.';$('coachText').textContent='Vamos un poco más profundo. Estás demostrando criterio financiero.'}
  else if(answered.some(a=>a.score===0)){$('coachKicker').textContent='UN PASO A LA VEZ';$('coachTitle').innerHTML='Detectarlo ya es<br>un avance.';$('coachText').textContent='Aquí hay una oportunidad para aprender. Seguimos sin juicios y a tu ritmo.'}
  else{$('coachKicker').textContent='TU COMPAÑERA DE VIAJE';$('coachTitle').innerHTML='Empecemos<br>por lo esencial.';$('coachText').textContent='No hay respuestas malas. Lo importante es saber dónde estás hoy.'}}
function getSectionScores(){return areas.map((area,index)=>{const values=Object.values(state.answers).filter(answer=>answer.area===index&&answer.score!==null).map(answer=>answer.score);return {area,index,answered:values.length,score:values.length?Math.round(values.reduce((sum,value)=>sum+value,0)/values.length*100):0}})}
function getSectionFeedback(areaIndex){const result=getSectionScores()[areaIndex],band=result.score>=80?'high':result.score>=60?'good':result.score>=40?'developing':'foundation';const messages=feedbackMessages[band];return {score:result.score,level:band==='high'?'Base sólida':band==='good'?'Buen nivel':band==='developing'?'En desarrollo':'Bases por fortalecer',message:messages[areaIndex%messages.length]}}
function getFinancialDiagnosis(sectionScores){const values=Object.values(state.answers).filter(answer=>answer.score!==null).map(answer=>answer.score),overall=Math.round(values.reduce((sum,value)=>sum+value,0)/Math.max(1,values.length)*100);const level=overall>=80?'Muy buen dominio financiero':overall>=60?'Buena base financiera':overall>=40?'Conocimientos financieros en desarrollo':'Una oportunidad para fortalecer tus bases financieras';const message=overall>=80?'Tu desempeño refleja una base consistente en varias áreas. Puedes seguir profundizando con objetivos concretos.':overall>=60?'Tienes una base funcional para tomar decisiones y algunos temas pueden darte todavía más seguridad.':overall>=40?'Tu mapa muestra conocimientos parciales y oportunidades claras para convertir ideas en hábitos.':'Este punto de partida puede crecer mucho con algunos conceptos fundamentales y pasos prácticos.';const ordered=[...sectionScores].filter(section=>section.answered>0).sort((a,b)=>b.score-a.score),focus=overall>=80?[]:ordered.slice(-2).reverse();return {overall,level,message,strengths:ordered.slice(0,3),focus}}
function getCourseOpportunity(course,sectionScores){const direct=course.questionRefs.map(reference=>state.answers[reference]).filter(answer=>answer&&answer.score!==null).map(answer=>answer.score);if(direct.length)return 1-direct.reduce((sum,value)=>sum+value,0)/direct.length;const related=course.areaIndices.map(index=>sectionScores[index]).filter(section=>section&&section.answered>0);return related.length?1-related.reduce((sum,section)=>sum+section.score,0)/related.length/100:null}
function getRecommendedCourses(sectionScores,diagnosis){const scored=courseRecommendations.map(course=>({...course,opportunity:getCourseOpportunity(course,sectionScores)})).filter(course=>course.opportunity!==null).sort((a,b)=>b.opportunity-a.opportunity);const meaningful=scored.filter(course=>course.opportunity>=.2).slice(0,2);return meaningful.length?meaningful:(diagnosis.overall>=80?courseRecommendations.map(course=>({...course,opportunity:null})):scored.slice(0,1))}
function renderInsightList(id,items,emptyText){$(id).innerHTML=items.length?items.map(item=>`<div class="insight-row"><strong>${item.area.name}</strong><span>${item.score}%</span></div>`).join(''):`<p class="empty-insight">${emptyText}</p>`}
function renderCourseCards(courses,diagnosis){$('recommendationIntro').textContent=diagnosis.overall>=80?'Tu desempeño es sólido. Estos cursos pueden ayudarte a profundizar, no porque te falte una base, sino para seguir creciendo.':'Elegimos estas opciones a partir de las áreas donde tienes más espacio para ganar claridad y confianza.';$('recommendations').innerHTML=courses.map((course,index)=>`<article class="course-card"><div class="course-thumbnail">${course.thumbnail?`<img src="${course.thumbnail}" alt="">`:'<img src="hpw.png" alt="Hispanic Wealth">'}</div><div class="course-copy"><span class="course-label">${index?'TAMBIÉN PODRÍA AYUDARTE':'TU PRÓXIMO PASO'}</span><h3>${course.name}</h3><p>${course.reason}</p><a class="course-link" href="${course.url}" target="_blank" rel="noopener">Conocer el curso <span>↗</span></a></div></article>`).join('')}
function unlockNavigation(){$('nextButton').disabled=!state.answers[key()];$('backButton').disabled=Object.keys(state.answers).length===0}
function fadeInQuestion(){const wrap=$('questionWrap');wrap.classList.remove('question-fade-out');void wrap.offsetWidth;wrap.classList.add('question-fade-in');setTimeout(()=>wrap.classList.remove('question-fade-in'),1000);unlockNavigation()}
function showSectionBreak(previousArea){const area=areas[state.area],feedback=getSectionFeedback(previousArea);$('sectionBreakTitle').textContent=area.name;$('sectionBreakText').textContent=areaIntroductions[state.area];$('sectionBreakScore').textContent=`${feedback.score}% · ${feedback.level}`;$('sectionBreakFeedback').textContent=feedback.message;$('sectionBreakProgress').textContent=`Área ${state.area+1} de ${areas.length}`;$('sectionBreak').hidden=false;$('continueSection').focus()}
function continueSection(){$('sectionBreak').hidden=true;$('questionWrap').classList.remove('section-paused');fadeInQuestion()}
function navigate(areaChanged,previousArea){const wrap=$('questionWrap');$('nextButton').disabled=true;$('backButton').disabled=true;wrap.classList.remove('question-fade-in');wrap.classList.add('question-fade-out');setTimeout(()=>{render();if(areaChanged){wrap.classList.add('section-paused');showSectionBreak(previousArea)}else fadeInQuestion()},1000)}
function next(){const a=state.answers[key()];if(!a)return;const previousArea=state.area;if(a.value==='no')state.wrong++;else if(a.score===1)state.wrong=0;
  const qs=areas[state.area].questions[levels[state.level]];if(state.index<qs.length-1 && state.wrong<3)state.index++;
  else if(state.level<2 && state.wrong<3){state.level++;state.index=0;state.wrong=0}
  else if(state.area<areas.length-1){state.area++;state.level=0;state.index=0;state.wrong=0}
  else return finish();save();navigate(state.area!==previousArea,previousArea)}
function back(){const keys=Object.keys(state.answers);if(!keys.length)return;const previousArea=state.area;const last=keys[keys.length-1].split('-').map(Number);delete state.answers[keys[keys.length-1]];[state.area,state.level,state.index]=last;save();navigate(state.area!==previousArea,previousArea)}
function finish(){save();const sectionScores=getSectionScores(),diagnosis=getFinancialDiagnosis(sectionScores),courses=getRecommendedCourses(sectionScores,diagnosis);$('finalScore').textContent=diagnosis.overall;$('finalLevel').textContent=diagnosis.level;$('finalMessage').textContent=diagnosis.message;$('scoreRing').style.setProperty('--score',`${diagnosis.overall*3.6}deg`);$('areaResults').innerHTML=sectionScores.map(section=>`<div class="area-row"><div class="area-meta"><span>${section.area.name}</span><strong>${section.score}%</strong></div><div class="area-line"><i style="width:${section.score}%"></i></div></div>`).join('');renderInsightList('strengths',diagnosis.strengths,'Cada área aporta información útil a tu mapa.');renderInsightList('focusAreas',diagnosis.focus,'Tu desempeño general es sólido; puedes elegir un tema para profundizar.');renderCourseCards(courses,diagnosis);show('resultsView');$('saveExit').hidden=true;localStorage.removeItem('claraProgress')}
function start(fresh=true){if(fresh){state={area:0,level:0,index:0,answers:{},learn:[],wrong:0};save()}show('quizView');$('saveExit').hidden=false;render()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)}
$('startButton').onclick=()=>start();$('resumeButton').onclick=()=>start(false);$('nextButton').onclick=next;$('backButton').onclick=back;$('saveExit').onclick=()=>{save();show('welcomeView');$('saveExit').hidden=true;toast('Progreso guardado en este dispositivo')};
$('continueSection').onclick=continueSection;
$('learnMore').onchange=e=>{state.learn=e.target.checked?[...new Set([...state.learn,key()])]:state.learn.filter(x=>x!==key());save()};$('restartButton').onclick=()=>start();
$('shareButton').onclick=async()=>{const text=`Mi diagnóstico financiero en Clara: ${$('finalScore').textContent}/100 — nivel ${$('finalLevel').textContent}.`;if(navigator.share)await navigator.share({title:'Mi diagnóstico financiero',text});else{await navigator.clipboard.writeText(text);toast('Resultado copiado al portapapeles')}};
$('downloadButton').onclick=()=>{window.print()};if(localStorage.getItem('claraProgress')){$('resumeButton').hidden=false;try{state=JSON.parse(localStorage.getItem('claraProgress'))}catch{localStorage.removeItem('claraProgress')}}

  